# baseURL
@baseURL = http://localhost:5000/api/user

###
# Create New Account
POST {{ baseURL }}/sign-up
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
    "firstName": "John" | "undefined",
    "lastName": "Doe" | "undefined",
    "role": "User",
    "status": "Active"
}

###
# User Login
POST {{ baseURL }}/log-in
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# User Logout
POST {{ baseURL }}/log-out
Content-Type: application/json
